const express = require('express');
const addBreedController = require('../controller/pet-breed-controller/add-breed-controller');
const updateBreedController= require('../controller/pet-breed-controller/update-breed-controller');
const deleteBreedController = require('../controller/pet-breed-controller/delete-breed-controller');
const addFoodController = require('../controller/pet-food-controller/add-food-controller');
const deleteFoodController = require('../controller/pet-food-controller/delete-food-controller');
const addClothesController = require('../controller/pet-clothes-controller/add-clothes-controller');
const updateClothesController = require('../controller/pet-clothes-controller/update-clothes-controller');
const deleteClothesController = require('../controller/pet-clothes-controller/delete-clothes-controller');
const addCategoryController = require('../controller/pet-category-controller/add-category-controller');
const updateCategoryController = require('../controller/pet-category-controller/update-category-controller');
const deleteCategoryController = require('../controller/pet-category-controller/delete-category-controller');
const addOrderController = require('../controller/pet-order-controller/add-order-controller');
const validateSchema = require('../validator/validate');
const {addFoodValidator,updateFoodValidator,deleteFoodValidator} = require('../validator/pet-food-validator/index');
const {addBreedValidator,updateBreedValidator,deleteBreedValidator}= require('../validator/pet-breed-validator/index');
const updateFoodController = require('../controller/pet-food-controller/update-food-controller');
const addOrderValidator = require('../validator/pet-order-validator/add-order-validator');
const {addClothesValidator,updateClothesValidator ,deleteClothesValidator}= require('../validator/pet-clothes-validator/index');
const { addCategoryValidator,updateCategoryValidator,deleteCategoryValidator} = require('../validator/pet-category-validator/index');
const { addBreedImage } = require('../controller/pet-breed-controller/add-breed-image');
const getFileSignedUrl = require('../common/get-signed-url');

const router = express.Router();
router.post('/addBreed',addBreedValidator,validateSchema,addBreedController);
router.put('/updateBreed/:breedId',updateBreedValidator,validateSchema,updateBreedController);
router.delete('/deleteBreed/:breedId',deleteBreedValidator,validateSchema,deleteBreedController);
router.post('/addFood',addFoodValidator,validateSchema,addFoodController);
router.put('/updateFood/:foodId',updateFoodValidator,validateSchema,updateFoodController);
router.delete('/deleteFood',deleteFoodValidator,validateSchema,deleteFoodController);
router.post('/addClothes',addClothesValidator,validateSchema,addClothesController);
router.put('/updateClothes/:clothesId',updateClothesValidator,validateSchema,updateClothesController);
router.delete('/deleteClothes',deleteClothesValidator,validateSchema,deleteClothesController);
router.post('/addCategory',addCategoryValidator,validateSchema,addCategoryController);
router.put('/updateCategory/:categoryId',updateCategoryValidator,validateSchema,updateCategoryController);
router.delete('/deleteCategory',deleteCategoryValidator,validateSchema,deleteCategoryController);
router.post('/addOrder',addOrderValidator,validateSchema,addOrderController);
router.post('/addImage',addBreedImage);
router.post('/getSignedUrl',getFileSignedUrl);
module.exports=router;